extra-keys = [[{key: 'ESC', popup: {macro: 'ESC c', display: 'CLR'}},{key: '/',popup: {macro: 'ESC e', display: 'EXIT'}},'-',{key: 'SHIFT'},'UP','HOME','PGDN','END'],['CTRL','ALT','TAB','LEFT','DOWN','RIGHT',{key: 'ALT', display: 'NL'},'BKSP']]

shortcut.create-session = ctrl+t
shortcut.next-session = ctrl+2
shortcut.previous-session = ctrl+1

# ESC+C = clear, ESC+E = exit
enforce-char-based-input = false
